-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgpzdJy4Bgl20xc6Wm
S6UBOIWP57UuGXpkenGYEusTGp+gCgYIKoZIzj0DAQehRANCAASh9X8KaI7Rp8NV
Ecq4MHtAzswwkGy/ccmYLaXnaNs9VaQ0q2dzHLqL8MEsHD0HXKnLD/40/nOpHZFV
QQXPQuic
-----END PRIVATE KEY-----